services:
  asr_serve:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "${RAY_FASTAPI_PORT:-8000}:8000"   # Inference API
      - "${RAY_DASHBOARD_PORT:-8265}:8265" # Dashboard API
    environment:
      - HF_HOME=/home/ray/.cache/huggingface
      - RAY_memory_monitor_refresh_ms=0
      - RAY_object_store_memory=4294967296
      - RAY_DASHBOARD_HOST=0.0.0.0
      - RAY_LOG_LEVEL=WARNING
      - RAY_SERVE_LOG_TO_STDERR=1
    volumes:
      - ${HOME}/.cache/huggingface:/home/ray/.cache/huggingface
      - type: tmpfs
        target: /tmp
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    shm_size: "16gb"
    tmpfs:
      - /dev/shm:size=16g
    restart: unless-stopped


